# ==============================================================================
# File: spark-api -> template.yaml
# Description: Creation of Spark API Specific Lambda Functions
# ==============================================================================

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  securityGroup:
    Type: String

  subnet1:
    Type: String

  subnet2:
    Type: String

  listingDatabase:
    Type: String

  rdsDatabase:
    Type: String

  mlsLambdaFunctionRole:
    Type: String


Resources:
  SparkActiveDataDownloadLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spark-active-data-download-func
      Handler: app.lambda_handler
      FunctionName: spark-active-data-download-func
      Description: "This lambda fetches data from source and dumps into DB"
      Runtime: python3.12
      Timeout: 900
      MemorySize: 1024
      Role: !Ref mlsLambdaFunctionRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref securityGroup
        SubnetIds:
          - !Ref subnet1
          - !Ref subnet2
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python312:16"
        - !Sub "arn:aws:lambda:${AWS::Region}:770693421928:layer:Klayers-p312-psycopg2-binary:1"
      Environment:
        Variables:
          listingDatabase: !Ref listingDatabase
          rdsDatabase: !Ref rdsDatabase
          bucket_name: !Sub idx-data-lake-${AWS::AccountId}-${AWS::Region}
          sqlExecLimit: 900000

  SparkActiveDataDownloadLambdaFunctionlogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SparkActiveDataDownloadLambdaFunction}"
      RetentionInDays: 90

  SparkInactiveDataDownloadLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spark-inactive-data-download-func
      Handler: app.lambda_handler
      FunctionName: spark-inactive-data-download-func
      Description: "This lambda fetches all active data from source and dumps into DB"
      Runtime: python3.12
      Timeout: 900
      MemorySize: 1024
      Role: !Ref mlsLambdaFunctionRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref securityGroup
        SubnetIds:
          - !Ref subnet1
          - !Ref subnet2
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python312:16"
        - !Sub "arn:aws:lambda:${AWS::Region}:770693421928:layer:Klayers-p312-psycopg2-binary:1"
      Environment:
        Variables:
          listingDatabase: !Ref listingDatabase
          rdsDatabase: !Ref rdsDatabase

  SparkInactiveDataDownloadLambdaFunctionlogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SparkInactiveDataDownloadLambdaFunction}"
      RetentionInDays: 90

  SparkOpenHouseDownloadUtilityLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spark-openhouse-download-utility-func
      Handler: app.lambda_handler
      # FunctionName: spark-openhouse-download-utility-func
      FunctionName: spark-inactive-openhouse-download-func
      Description: "This lambda fetches valid openhouse records from source and dumps into DB"
      Runtime: python3.12
      Timeout: 900
      MemorySize: 1024
      Role: !Ref mlsLambdaFunctionRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref securityGroup
        SubnetIds:
          - !Ref subnet1
          - !Ref subnet2
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python312:16"
        - !Sub "arn:aws:lambda:${AWS::Region}:770693421928:layer:Klayers-p312-psycopg2-binary:1"
      Environment:
        Variables:
          listingDatabase: !Ref listingDatabase
          rdsDatabase: !Ref rdsDatabase

  SparkOpenHouseDownloadUtilityLambdaFunctionlogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SparkOpenHouseDownloadUtilityLambdaFunction}"
      RetentionInDays: 90

  SparkMissingSoldDatePriceUtilityLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spark-missing-sold-date-price-utility-func
      Handler: app.lambda_handler
      # FunctionName: spark-missing-sold-date-price-utility-func
      FunctionName: spark-missing-sold-date-utility-func
      Description: "This lambda fetches sold date and sold price from source and updates in DB where listing_p_sold records have null sold_date or sold_price"
      Runtime: python3.12
      Timeout: 900
      MemorySize: 1024
      Role: !Ref mlsLambdaFunctionRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref securityGroup
        SubnetIds:
          - !Ref subnet1
          - !Ref subnet2
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python312:16"
        - !Sub "arn:aws:lambda:${AWS::Region}:770693421928:layer:Klayers-p312-psycopg2-binary:1"
      Environment:
        Variables:
          listingDatabase: !Ref listingDatabase
          rdsDatabase: !Ref rdsDatabase

  SparkMissingSoldDatePriceUtilityLambdaFunctionlogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SparkMissingSoldDatePriceUtilityLambdaFunction}"
      RetentionInDays: 90

  SparkMetadataDownloadLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: spark-metadata-download-func
      Handler: app.lambda_handler
      FunctionName: spark-metadata-download-func
      Description: "This lambda fetches metadata from source and dumps into metadata tables"
      Runtime: python3.12
      Timeout: 900
      MemorySize: 1024
      Role: !Ref mlsLambdaFunctionRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref securityGroup
        SubnetIds:
          - !Ref subnet1
          - !Ref subnet2
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python312:16"
        - !Sub "arn:aws:lambda:${AWS::Region}:770693421928:layer:Klayers-p312-psycopg2-binary:1"
      Environment:
        Variables:
          listingDatabase: !Ref listingDatabase
          rdsDatabase: !Ref rdsDatabase

  SparkMetadataDownloadLambdaFunctionlogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SparkMetadataDownloadLambdaFunction}"
      RetentionInDays: 90