AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  securityGroup:
    Type: String

  subnet1:
    Type: String

  subnet2:
    Type: String

  listingDatabase:
    Type: String

  rdsDatabase:
    Type: String
  
  mlsLambdaFunctionRole:
    Type: String

Resources:
  DdfapiInactiveDataDownloadLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ddfapi-inactive-data-download-func
      Handler: app.lambda_handler
      FunctionName: ddfapi-inactive-data-download-func
      Description: "This lambda downloads data from the source and dumps it into pre-stage tables."
      Runtime: python3.12
      Timeout: 900
      MemorySize: 1024
      Role: !Ref mlsLambdaFunctionRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref securityGroup
        SubnetIds:
          - !Ref subnet1
          - !Ref subnet2
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python312:16"
        - !Sub "arn:aws:lambda:${AWS::Region}:770693421928:layer:Klayers-p312-psycopg2-binary:1"

      Environment:
        Variables:
          listingDatabase: !Ref listingDatabase
          rdsDatabase: !Ref rdsDatabase
  
  DdfapiInactiveDataDownloadLambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: DdfapiInactiveDataDownloadLambdaFunction
    Properties:
      LogGroupName: !Sub "/aws/lambda/${DdfapiInactiveDataDownloadLambdaFunction}"
      RetentionInDays: 90


Outputs:
  DdfapiInactiveDataDownloadLambdaFunction:
    Description: "DdfapiInactiveDataDownloadLambdaFunction"
    Value: !GetAtt DdfapiInactiveDataDownloadLambdaFunction.Arn