AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Glue Database for MLS S3 Data Lake"

Resources:
  GlueDatabase:
    Type: AWS::Glue::Database
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: idx_datalake
        Description: "Glue database for MLS S3 data lake"
